spring:
  application:
    name: analytics-service
  datasource:
    url: jdbc:h2:mem:analytics
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info